### ISSUE TITLE
Getting java.io.IOException: Unexpected response code for CONNECT: 400

### ISSUE THREAD

**Issue by MajedurRahmanMmr** [LarryDpk/Google-Bard#1]

**Comment by LarryDpk** [comment]
Hi @MajedurRahmanMmr , `Google Bard` is only available in US/UK, please make sure the network is connected.

**Comment by LarryDpk** [comment]
And make sure you have the right Session ID, It a cookie named `__Secure-1PSID`.

**Comment by LarryDpk** [comment]
As no response for a long time, will close it.
