### ISSUE TITLE
Getting NO_ANSWER Response 

### ISSUE THREAD

**Issue by ahmadkhalifah** [LarryDpk/Google-Bard#12]
Hi,

I started getting NO_ANSWER from yesterday. I tried to update the token but still the same response.

From the debug logs, it seems the answer is getting retrieved but the answer.getStatus() is returning NO_ANSWER.

15:04:33.638 [main] INFO com.pkslow.ai.util.WebUtils - Creating OkHttpClient with timeout PT5M
15:04:33.907 [main] INFO com.pkslow.ai.util.WebUtils - OkHttpClient created
15:04:35.087 [main] INFO com.pkslow.ai.GoogleBardClient - getSNlM0e Response code: 200
15:04:35.375 [main] INFO com.pkslow.ai.GoogleBardClient - calling Bard with request BardRequest{strSNlM0e=AJWyuYUjDH_9NAY6TKznEr2tVPRV:1687867475189, question=What is the date today?, conversationId=, responseId=, choiceId=}
15:04:37.866 [main] INFO com.pkslow.ai.GoogleBardClient - Ask Response code: 200
15:04:38.500 [main] DEBUG com.pkslow.ai.GoogleBardClient - Result for ask: [["wrb.fr",null,"[null,[\"c_2db4888103d20c51\",\"r_2db4888103d20772\"],[[\"what is the date today\",1],[\"Is it 365 day today?\",4],[\"How do I write today's date?\",4]],null,[[\"rc_2db4888103d20f17\",[\"Today is Tuesday, June 27, 2023.\"],[],null,null,null,true,null,null,\"en\",null,null,[null,null,null,null,null,[[]]]],[\"rc_2db4888103d20a38\",[\"As of today, June 27, 2023, it is Tuesday. The current time is 05:04:37 PST.\"],[],null,null,null,true,null,null,\"en\",null,null,[null,null,null,null,null,[[]]]],[\"rc_2db4888103d20559\",[\"Today is Tuesday, June 27, 2023. It is 05:04:37 PST in Pacific Standard Time (PST).\"],[],null,null,null,true,null,null,\"en\",null,null,[null,null,null,null,null,[[]]]]],[\"Jeddah Saudi Arabia\",\"SWML_DESCRIPTION_FROM_YOUR_PLACES_HOME\",false,[[[null,null,null,[[300,200],14]]],[[2,null,null,null,null,[[[[215642548,391786194],60,null,null,null,null,true]],null,[1]]]],null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,[null,null,null,null,null,null,null,true]],\"//www.google.com/maps/vt/data\\u003dx_l8kLOq5C-m9VrL5DJKPb7sDFIjWntSsXhIFvoUvEcgOdC4uI744UaaRqOi-PeoNHNY4evEvL9yR3Yv6fwXM-3byP2xAPBq_plMmNlSwxEHEJmH0FT3xJvSCbIYPrQXpS4GAqfwIpQ\"],null,null,\"SA\"]"]]
15:04:38.500 [main] DEBUG com.pkslow.ai.GoogleBardClient - Raw answers length: 1242

**Comment by kharemohit786** [comment]
Getting the same issue, Is there any update on the fix?

**Comment by LarryDpk** [comment]
Will check and fix

**Comment by denmark-dangnagui** [comment]
i also have the same issue. if you fix this issue, i really appreciate it.

**Comment by LarryDpk** [comment]
It's due to `Google Bard` has changed the result format. Will fix.

**Comment by denmark-dangnagui** [comment]
really appreciate it.

**Comment by LarryDpk** [comment]
please wait for a while and have a try with version `0.3.3`. The lib need some time to sync.

**Comment by kharemohit786** [comment]
There is again some issue with 0.3.4, getting below error, if can be fixed, thanks.
`java.lang.NullPointerException: Parameter specified as non-null is null: method okhttp3.FormBody$Builder.add, parameter value`
`java.lang.RuntimeException: Can't access to Google Bard`
