### ISSUE TITLE
Avoid Lombok as transitive dependency 

### ISSUE THREAD

**Issue by jabrena** [LarryDpk/Google-Bard#15]
Hi, I was reviewing the repository and I noticed that Lombok is defined as transitive dependency but it is not necessary. It could generate the code and not need to be considered as required dependency.

```xml
<dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>compile</scope>
        </dependency>
```

Do you accept a PR to avoid it?

Juan Antonio

**Comment by LarryDpk** [comment]
Yes, you can raise PR and I will review

**Comment by LarryDpk** [comment]
The lombok is `compile` scope, any concern ?

**Comment by jabrena** [comment]
Apologies the delay but I am on holidays. With scope compile scope, you force all consumer to use lombok, it is better to use  an annotationProcessor approach:

https://projectlombok.org/setup/maven

In the another hand if next Java LTS version is Java 21, why try to maintain backward compatibility to Java 8?
Spring Boot 3 requires java 17.

What do you think?

Juan Antonio

**Comment by LarryDpk** [comment]
updated the `scope` to `provided`. would not update JDK to 8 now, it will cause compatibility issue

**Comment by LarryDpk** [comment]
close it as no more response
