### ISSUE TITLE
Getting frequent errors with java.lang.RuntimeException: Can't access to Google Bard

### ISSUE THREAD

**Issue by kharemohit786** [LarryDpk/Google-Bard#17]
Getting frequent erros with below
`08:49:39.727 [http-nio-8080-exec-1] ERROR com.pkslow.ai.GoogleBardClient - Failed to get answer: 
java.lang.NullPointerException: Parameter specified as non-null is null: method okhttp3.FormBody$Builder.add, parameter value`

Previously it worked by changing the token from cookie, but now it does not seem to work even after updating the new token from `__Secure-1PSID`
Could you help to verify if something changed on Bard api side.

**Comment by kharemohit786** [comment]
Can I fetch this token from google authentication tokens somehow rather taking it from browsers everytime?

**Comment by ahmadkhalifah** [comment]
I am getting the same issue. It started with me few days ago then it worked after updating the key, now it is not, even after updating the key.
Answer(status=ERROR, chosenAnswer=null, images=null)

**Comment by LarryDpk** [comment]
will check this issue

**Comment by LarryDpk** [comment]
issue fix with version `0.3.5`, now need two cookies: `$__Secure-1PSID;$__Secure-1PSIDTS`

<img width="1525" alt="image" src="https://github.com/LarryDpk/Google-Bard/assets/9039939/5eb03069-1be0-4a3b-a075-a393b7a3f9a0">
