### ISSUE TITLE
Answer.getStatus() = ERROR

### ISSUE THREAD

**Issue by ahmadkhalifah** [LarryDpk/Google-Bard#20]
The issue with the response is still persisting.

An ERROR when trying to retrieve the answer.  (answer.getStatus() => ERROR)

Using latest <version>0.3.5</version> with key combinations ($__Secure-1PSID;$__Secure-1PSIDTS) as the token. 

Kindly check.

**Comment by LarryDpk** [comment]
Interesting. I tried again and it worked for me

**Comment by ahmadkhalifah** [comment]
Yes, I tried to get fresh cookies and it worked finally, many thanks!

**Comment by ahmadkhalifah** [comment]
I noticed that the $__Secure-1PSIDTS gets expired and I have to update it in the code frequently.

**Comment by LarryDpk** [comment]
yes. Google bard restriction

**Comment by ahmadkhalifah** [comment]
LarryDpk, appreciate all your efforts.

__Secure-1PSIDTS token seems not always available in the cookies. Also, when it is there, it is not working for me anymore.

**Comment by LarryDpk** [comment]
my account still ok. I think should be Goolge restriction......

**Comment by LarryDpk** [comment]
close as no more reply
