### ISSUE TITLE
Parameter specified as non-null is null: method okhttp3.FormBody$Builder.add, parameter value

### ISSUE THREAD

**Issue by estebangarciaalonso** [LarryDpk/Google-Bard#22]
Getting frequent erros with below
08:49:39.727 [http-nio-8080-exec-1] ERROR com.pkslow.ai.GoogleBardClient - Failed to get answer:  java.lang.NullPointerException: Parameter specified as non-null is null: method okhttp3.FormBody$Builder.add, parameter value

it is still happening with version 0.3.5 and passing the 2 tokens ...

**Comment by LarryDpk** [comment]
can you try to reload the project and try again? It's ok on my side with two token: `$__Secure-1PSID;$__Secure-1PSIDTS`

**Comment by estebangarciaalonso** [comment]
I apologize! There was a refresh issue on my end! You were right and it is working!
