### ISSUE TITLE
Answer in XML or JSON format returns java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ahmadkhalifah** [LarryDpk/Google-Bard#8]
I am trying to have get an answer in xml or json format. I am getting an exception whenever I trigger the ask method.

I tried the following:
Question: write the sequence from one to ten in xml format. 

15:12:28.657 [main] INFO com.pkslow.ai.GoogleBardClient - Ask Response code: 400
15:12:28.672 [main] ERROR com.pkslow.ai.GoogleBardClient - Failed to get answer: 
java.lang.IllegalStateException: Can't get the answer
	at com.pkslow.ai.GoogleBardClient.callBardToAsk(GoogleBardClient.java:98)
	at com.pkslow.ai.GoogleBardClient.ask(GoogleBardClient.java:53)
	at com.ak.articlebot.FeedConsumer.main(FeedConsumer.java:53)

**Comment by LarryDpk** [comment]
Which version you used? Could you provide more log?
latest version with the answer:

## write the sequence from one to ten in xml format
0:30:30.041 [main] INFO com.pkslow.ai.GoogleBardExample -- Markdown:
Sure, here is the sequence from 1 to 10 in XML format:

```xml
<sequence>
  <number>1</number>
  <number>2</number>
  <number>3</number>
  <number>4</number>
  <number>5</number>
  <number>6</number>
  <number>7</number>
  <number>8</number>
  <number>9</number>
  <number>10</number>
</sequence>
```

Do you want to try other XML formats?


## write the sequence from one to ten in json format
20:31:55.326 [main] INFO com.pkslow.ai.GoogleBardExample -- Markdown:
Sure, here is the sequence from 1 to 10 in JSON format:

```json
{
  "sequence": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10
  ]
}
```

Here is a breakdown of the JSON code:

* The `sequence` key is a string that represents the name of the array.
* The array itself is enclosed in square brackets.
* Each element in the array is a number.
* The numbers are separated by commas.

I hope this helps! Let me know if you have any other questions.

**Comment by ahmadkhalifah** [comment]
It seems I had an older version, now it is working fine. Many thanks!

**Comment by LarryDpk** [comment]
no problem

**Comment by ahmadkhalifah** [comment]
FYI
I noticed that whenever there is a return character (\r) in the prompt, I get the exception.

**Comment by LarryDpk** [comment]
Thanks for the info, could you share me the `question` and the answer body?
