### ISSUE TITLE
Request prompt cannot deal with escape characters. Such as “” quotation marks.

### ISSUE THREAD

**Issue by SherlockZh** [LarryDpk/Google-Bard#9]
Hi,

If my input prompt is: `What do you think of "Apple Vision Pro"?`, then it returrned 400. 
But if I remove quoation marks like: `What do you think of Apple Vision Pro?`, then it works fine.
<img width="1972" alt="image" src="https://github.com/LarryDpk/Google-Bard/assets/8073697/954cb4ce-3ca9-48b8-96aa-6f1558973d0f">

<img width="2145" alt="image" src="https://github.com/LarryDpk/Google-Bard/assets/8073697/5af227d8-890c-47f9-b8a0-57b798cfe5a0">

And actually I want to send json text in my prompt which will contains `"`, `\n`, `\t`, etc. So my guess is all these escape needed characters were not handled. I also looked up okHttp doc to find a solution and tried to made some code change but not succeed. So here to ask for help. Thank you.

**Comment by SherlockZh** [comment]
Resolved. By changing prompt to `What do you think of \\\"Apple Vision Pro\\\"?`.

**Comment by LarryDpk** [comment]
I also fixed in version 0.3.1 for `"`

**Comment by falniak95** [comment]
When I send a question with `"'` it's returning the same exception, for your information!
